spring.application.name=peoplehubbackend

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/peoplehub
spring.datasource.username=peoplehub
spring.datasource.password=peoplehub123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.output.ansi.enabled=ALWAYS